[package]
name = "vellogd-client"
version = "0.1.0"
edition = "2021"

[dependencies]
vellogd-protocol = { path = "../vellogd-protocol/" }

tonic = "0.12"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
